// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAIResponse(arg1) {
	return window["go"]["services"]["CheaterService"]["GetAIResponse"](arg1);
}

export function TranscribeAudio(arg1) {
	return window["go"]["services"]["CheaterService"]["TranscribeAudio"](arg1);
}
