// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MinimizeWindow():Promise<void>;

export function Quit():Promise<void>;

export function RestoreWindow():Promise<void>;

export function SetOpacity(arg1:number):Promise<void>;
