// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAPIKeys():Promise<Record<string, boolean>>;

export function MinimizeWindow():Promise<void>;

export function ProcessAudio(arg1:main.AudioData):Promise<main.ProcessAudioResponse>;

export function Quit():Promise<void>;

export function RestoreWindow():Promise<void>;

export function SetOpacity(arg1:number):Promise<void>;
