// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAPIKeys() {
	return window["go"]["main"]["App"]["CheckAPIKeys"]();
}

export function GetAIResponse(arg1) {
	return window["go"]["main"]["App"]["GetAIResponse"](arg1);
}

export function MinimizeWindow() {
	return window["go"]["main"]["App"]["MinimizeWindow"]();
}

export function Quit() {
	return window["go"]["main"]["App"]["Quit"]();
}

export function RestoreWindow() {
	return window["go"]["main"]["App"]["RestoreWindow"]();
}

export function SetOpacity(arg1) {
	return window["go"]["main"]["App"]["SetOpacity"](arg1);
}

export function TranscribeAudio(arg1) {
	return window["go"]["main"]["App"]["TranscribeAudio"](arg1);
}
