// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAPIKeys() {
  return window['go']['main']['App']['CheckAPIKeys']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function ProcessAudio(arg1) {
  return window['go']['main']['App']['ProcessAudio'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestoreWindow() {
  return window['go']['main']['App']['RestoreWindow']();
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}
